[package]
name = "axiusflow_local_history"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axiusflow_local_storage = { path = "../local_storage" }
axiusflow_provider_history = { path = "../provider_history" }

[lints]
workspace = true
