[package]
name = "axiusflow_linux_dpdk_adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
build = "build.rs"

[features]
default = []
native = []

[dependencies]
axiusflow_transport = { path = "../../transport" }

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"
