[package]
name = "axiusflow_terminal_ui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axiusflow_instruments = { path = "../../domain/instruments" }
axiusflow_design_system = { path = "../design_system" }
axiusflow_market_data = { path = "../../domain/market_data" }
gpui.workspace = true

[lints]
workspace = true
