[package]
name = "axiusflow_market_data_plane"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axiusflow_application = { path = "../../crates/application" }
axiusflow_coinbase_market_adapter = { path = "../../crates/adapters/coinbase_market" }
axiusflow_instruments = { path = "../../crates/domain/instruments" }
axiusflow_market_data = { path = "../../crates/domain/market_data" }
axiusflow_market_protocol_adapter = { path = "../../crates/adapters/market_protocol" }
axiusflow_protocols = { path = "../../crates/protocols" }
rustls.workspace = true
serde.workspace = true
serde_json.workspace = true
tungstenite.workspace = true
webpki-roots.workspace = true

[lints]
workspace = true
