[package]
name = "axiusflow_linux_af_xdp_adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
native-copy = ["dep:libxdp-sys", "dep:xsk-rs"]

[dependencies]
axiusflow_transport = { path = "../../transport" }

[target.'cfg(target_os = "linux")'.dependencies]
libxdp-sys = { version = "=0.2.4", features = ["use_cc_build"], optional = true }
xsk-rs = { version = "=0.8.0", optional = true }

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"
