[package]
name = "axiusflow_local_engine_client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
axiusflow_engine_protocol = { path = "../engine_protocol" }
axiusflow_platform_runtime = { path = "../platform_runtime" }
getrandom.workspace = true
interprocess.workspace = true
zeroize.workspace = true

[lints]
workspace = true
