[package]
name = "aeris_application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
aeris_instruments = { path = "../domain/instruments" }
aeris_market_data = { path = "../domain/market_data" }
sha2.workspace = true

[lints]
workspace = true
