[package]
name = "axiusflow_platform_runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
ed25519-dalek.workspace = true
serde.workspace = true
serde_json.workspace = true
semver.workspace = true
same-file.workspace = true
sha2.workspace = true
sysinfo.workspace = true
ureq.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
wayland-client.workspace = true
wayland-protocols.workspace = true
zbus.workspace = true

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
signal-hook = "=0.4.4"

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
keyring.workspace = true
notify-rust.workspace = true

[target.'cfg(any(target_os = "macos", target_os = "windows"))'.dependencies]
display-info.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Graphics_Dwm",
    "Win32_Graphics_Gdi",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Networking_WinSock",
    "Win32_Storage_FileSystem",
    "Win32_System_Performance",
    "Win32_System_IO",
    "Win32_System_LibraryLoader",
    "Win32_System_Power",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }

[build-dependencies]
embed-resource.workspace = true

[lints.rust]
unsafe_code = "deny"

[lints.clippy]
all = "warn"
pedantic = "warn"
