#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

cargo test --locked --package axiusflow_desktop_provider_runtime

echo "desktop_provider_runtime=passed cases=29 vault_credentials=true public_keyless_vault_bypass=true credential_bytes_bounded=true credential_bytes_zeroized=true session_generation_fencing=true bounded_semantic_queue=true immutable_publication=true overflow_recovery=true overflow_retires_history_handoffs=true unconfirmed_stop_blocks_replacement=true environmental_events_retained_during_cleanup=true interleaved_power_network_ordering=true idle_environmental_cycles_do_not_connect=true public_connect_respects_environment=true drop_attempts_session_stop=true publication_event_debug_redacted=true history_errors_redacted=true redacted_diagnostics=true suspend_resume_recovery=true network_change_recovery=true worker_thread_ownership=true history_composition=true history_callbacks_generation_fenced=true lifecycle_retires_history_handoffs=true history_handoff_bound=true local_hydration_provider_independent=true local_hydration_control_plane_independent=true coinbase_history_scheduler_completion=true completion_identity_fenced=true completion_pagination_fenced=true completion_continuity_fenced=true coinbase_streaming_driver=true streaming_callback_bound=true streaming_callback_source_bound=true streaming_callback_overflow_classified=true streaming_connect_stop_bound=true streaming_stop_generation_fenced=true streaming_trade_debug_redacted=true coinbase_trade_to_bar=true coinbase_history_seed=true malformed_trade_invalidation=true native_network_monitor=linux_implemented native_network_monitor_wiring=not_implemented gpui_integration=not_implemented cloud_absence_proof=not_claimed"
